@isTest
private class CallbackTest {
    @isTest static void CallbackConsumerKeySecretTest() {
   //     CallbackConsumerKeySecret callback = new CallbackConsumerKeySecret();
   //     Metadata.DeployCallbackContext context = new Metadata.DeployCallbackContext();
   //     
   //     Metadata.DeployResult resultSuccess = new Metadata.DeployResult();
   //     resultSuccess.status = Metadata.DeployStatus.Succeeded;
   //     
   //     Metadata.DeployResult resultFail = new Metadata.DeployResult();
   //     resultFail.numberComponentErrors = 1;
//
   //     Test.startTest();
   //     try {
   //         callback.handleResult(resultSuccess, context);
   //     } catch(DmlException e) {
   //         system.assert(false, e);
   //     }
//
   //     try {
   //         callback.handleResult(resultFail, context);
   //     } catch(DmlException e) {
   //         system.assert(true, 'Success catch the error');
   //     }
   //     Test.stopTest();
    }
}

